- hosts: all
  become: yes
  roles:
    - role: manage_user
      vars:
        user_name: "superuser"
        user_ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQ..."
        user_password_manage: true
        user_password: "$6$rounds=656000$WX6bUJ5dtzQx9Ni/$6XewumE7W2nGZ1HcR9ZrO2YQYMS0vL7sFZQ7yY2X..."
        user_sudo_nopasswd: false  # требовать пароль для sudo