---
- name: Ensure group exists
  group:
    name: "{{ ansible_user }}"
    state: present

- name: Ensure user exists
  user:
    name: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    groups: "{{ ansible_user_groups }}"
    append: yes
    shell: "{{ ansible_user_shell }}"
    home: "{{ ansible_user_home }}"
    state: present
    system: no
    create_home: yes

- name: Ensure .ssh directory exists
  file:
    path: "{{ ansible_user_home }}/.ssh"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0700

- name: Add authorized key
  template:
    src: authorized_keys.j2
    dest: "{{ ansible_user_home }}/.ssh/authorized_keys"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600

- name: Ensure sudoers file exists
  copy:
    dest: "/etc/sudoers.d/{{ ansible_user }}"
    content: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL\n"
    validate: "visudo -cf %s"